version: "3.4"

services:
  function:
    build: .
    env_file:
      - .env
    ports:
      - 9000:8080
    depends_on:
      - db
    volumes:
      - .:/var/task

  db:
    platform: linux/x86_64
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
